[package]
name = "sve_backend"
version = "2.2.4"
edition = "2021"
description = "Backend for the SVE website"
authors = ["Michael Seele <mseele@gmail.com>"]
license = "MIT"
repository = "https://github.com/mseele/sve-backend"
homepage = "https://github.com/mseele/sve-backend"
readme = "README.md"
publish = false

[dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [
  "fmt",
  "json",
  "env-filter",
] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
axum =  "0.7.7"
http-body-util = "0.1.2"
hyper = "1.4.1"
tower = "0.5.1"
tower-http = { version = "0.6.1", features = ["trace", "cors"] }
anyhow = { version = "1.0.89", features = ["backtrace"] }
mime = "0.3.17"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
base64 = "0.22.1"
base64-serde = "0.8.0"
chrono = { version = "0.4.24", default-features = false, features = [
  "clock",
  "std",
  "serde",
  "unstable-locales",
] }
chrono-tz = "0.9.0"
google-calendar3 = "5.0.2"
yup-oauth2 = "8.2.0"
hyper-legacy = { package = "hyper", version = "0.14.28" }
hyper-rustls = "0.24.0"
lettre = { version = "0.11.9", default-features = false, features = [
  "smtp-transport",
  "pool",
  "hostname",
  "builder",
  "tokio1-rustls-tls",
  "tracing",
] }
regex = "1.11.0"
lazy_static = "1.5.0"
csv = "1.2.1"
encoding = "0.2.33"
bigdecimal = { version = "0.4.5", features = ["serde"] }
sqlx = { version = "0.8.2", features = [
  "postgres",
  "runtime-tokio-rustls",
  "chrono",
  "bigdecimal",
] }
itertools = "0.13.0"
harsh = "0.2.2"
handlebars = "6.1.0"
simple_excel_writer = { version = "0.2.0", features = ["chrono"] }
printpdf = { version = "0.7.0", features = ["svg", "embedded_images"] }
image = "0.24.6"
cfg = "0.9.0"
lambda_http = { version = "0.13.0", default-features = false, features = [
  "apigw_http",
] }
tower-service = "0.3.3"
urlencoding = "2.1.3"

[dev-dependencies]
pretty_assertions = "1.4.1"

[profile.release]
# 2/true is too much, 0 is not enough, 1 is just right for backtraces
debug = 1
