[package]
name = "sve_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
env_logger = "0.9"
log = "0.4"
actix-web = "4.0"
actix-cors = "0.6"
anyhow = { version = "1.0", features = ["backtrace"] }
mime = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"
base64-serde = "0.6"
chrono = { version = "0.4", features = ["serde", "unstable-locales"] }
chrono-tz = { version = "0.6" }
googapis = { version = "0.6", features = ["google-firestore-v1"] }
gouth = { version = "0.2" }
tonic = { version = "0.6", features = ["tls"] }
google-sheets4 = "2.0"
google-calendar3 = "2.0"
yup-oauth2 = "5.1"
hyper = "0.14"
hyper-rustls = "0.22"
steel-cent = "0.2"
lettre = { version = "0.10.0-rc.4", features = ["tokio1-native-tls"] }
regex = "1.5"
