[package]
name = "sve_backend"
version = "2.0.8"
edition = "2021"
description = "Backend for the SVE website"
authors = ["Michael Seele <mseele@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mseele/sve-backend"
homepage = "https://github.com/mseele/sve-backend"
readme = "README.md"
publish = false

[dependencies]
openssl = { version = "0.10.48", features = ["vendored"] }
env_logger = "0.10.0"
log = "0.4.17"
actix-web = "4.2.1"
actix-cors = "0.6.4"
anyhow = { version = "1.0.68", features = ["backtrace"] }
mime = "0.3.16"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
base64 = "0.13.1"
base64-serde = "0.6.1"
chrono = { version = "0.4.23", features = ["serde", "unstable-locales"] }
chrono-tz = "0.8.1"
google-calendar3 = "4.0.1"
yup-oauth2 = "7.0.1"
hyper = "0.14.23"
hyper-rustls = "0.23.2"
lettre = { version = "0.10.1", features = ["tokio1-native-tls"] }
regex = "1.7.0"
lazy_static = "1.4.0"
csv = "1.1.6"
encoding = "0.2.33"
bigdecimal = { version = "0.3.0", features = ["serde"] }
sqlx = { version = "0.6.2", features = [
  "postgres",
  "runtime-tokio-rustls",
  "chrono",
  "bigdecimal",
  "offline",
] }
itertools = "0.10.5"
harsh = "0.2.2"
handlebars = "4.3.6"
simple_excel_writer = { version = "0.2.0", features = ["chrono"] }
printpdf = { version = "0.5.3", features = ["svg", "embedded_images"] }
image = "0.24.5"

[dev-dependencies]
pretty_assertions = "1.3.0"

[profile.release]
# 2/true is too much, 0 is not enough, 1 is just right for backtraces
debug = 1
