[package]
name = "sve_backend"
version = "2.0.0"
edition = "2021"
description = "Backend for the SVE website"
authors = ["Michael Seele <mseele@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mseele/sve-backend"
homepage = "https://github.com/mseele/sve-backend"
readme = "README.md"
publish = false

[package.metadata.release]
pre-release-replacements = [
  { file = "CHANGELOG.md", search = "Unreleased", replace = "{{version}}", min = 1 },
  { file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", exactly = 1 },
  { file = "CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}", min = 1 },
  { file = "CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly = 1 },
  { file = "CHANGELOG.md", search = "<!-- next-url -->", replace = "<!-- next-url -->\n[Unreleased]: https://github.com/mseele/sve-backend/compare/{{tag_name}}...HEAD", exactly = 1 },
]

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
env_logger = "0.9"
log = "0.4"
actix-web = "4.0"
actix-cors = "0.6"
anyhow = { version = "1.0", features = ["backtrace"] }
mime = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"
base64-serde = "0.6"
chrono = { version = "0.4", features = ["serde", "unstable-locales"] }
chrono-tz = { version = "0.6" }
google-calendar3 = "3.1"
yup-oauth2 = "6.6"
hyper = "0.14"
hyper-rustls = "0.23"
lettre = { version = "0.10.0-rc.6", features = ["tokio1-native-tls"] }
regex = "1.5"
lazy_static = "1.4.0"
csv = "1.1"
encoding = "0.2"
bigdecimal = { version = "0.3", features = ["serde"] }
sqlx = { version = "0.6", features = [
  "postgres",
  "runtime-tokio-rustls",
  "chrono",
  "bigdecimal",
  "offline",
] }
itertools = "0.10"
harsh = "0.2"
handlebars = "4.3"
xlsxwriter = "0.4"
uuid = { version = "1.2", features = ["v4", "fast-rng"] }

[dev-dependencies]
pretty_assertions = "1.2"

[profile.release]
# 2/true is too much, 0 is not enough, 1 is just right for backtraces
debug = 1
