[package]
name = "sve_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.3"
anyhow = "1.0"
mime = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
googapis = { version = "0.6", features = ["google-firestore-v1"] }
gouth = { version = "0.2" }
tonic = { version = "0.6", features = ["tls"] }
