[package]
name = "sve_backend"
version = "2.0.15"
edition = "2021"
description = "Backend for the SVE website"
authors = ["Michael Seele <mseele@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mseele/sve-backend"
homepage = "https://github.com/mseele/sve-backend"
readme = "README.md"
publish = false

[dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [
  "fmt",
  "json",
  "env-filter",
] }
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.6.18", features = ["headers"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace", "cors"] }
anyhow = { version = "1.0.70", features = ["backtrace"] }
mime = "0.3.17"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
base64 = "0.21.0"
base64-serde = "0.7.0"
chrono = { version = "0.4.24", default-features = false, features = [
  "clock",
  "std",
  "serde",
  "unstable-locales",
] }
chrono-tz = "0.8.2"
google-calendar3 = "5.0.2"
yup-oauth2 = "8.2.0"
hyper = "0.14.26"
hyper-rustls = "0.24.0"
lettre = { version = "0.10.4", default-features = false, features = [
  "smtp-transport",
  "pool",
  "hostname",
  "builder",
  "tokio1-rustls-tls",
] }
regex = "1.7.3"
lazy_static = "1.4.0"
csv = "1.2.1"
encoding = "0.2.33"
bigdecimal = { version = "0.3.0", features = ["serde"] }
sqlx = { version = "0.7.1", features = [
  "postgres",
  "runtime-tokio-rustls",
  "chrono",
  "bigdecimal",
] }
itertools = "0.11.0"
harsh = "0.2.2"
handlebars = "4.3.6"
simple_excel_writer = { version = "0.2.0", features = ["chrono"] }
printpdf = { version = "0.5.3", features = ["svg", "embedded_images"] }
image = "0.24.6"
cfg = "0.6.2"
lambda_http = { version = "0.8.1", default-features = false, features = [
  "apigw_http",
] }
tower-service = "0.3.2"
urlencoding = "2.1.3"

[dev-dependencies]
pretty_assertions = "1.3.0"

[profile.release]
# 2/true is too much, 0 is not enough, 1 is just right for backtraces
debug = 1
