name: Setup, Build, and Publish
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  IMAGE: sve_backend
  REGISTRY_HOSTNAME: eu.gcr.io/sve-backend

jobs:
  setup-build-and-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo & target directories
        uses: swatinem/rust-cache@v2

      - name: Install musl
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools

      - name: Configure secrets
        run: |
          mkdir -p secrets
          echo ${{ secrets.SVE_CREDENTIALS_ENCODED }} | base64 -d > secrets/credentials.json
          echo ${{ secrets.SVE_EMAILS_ENCODED }} | base64 -d > secrets/email.json
          echo ${{ secrets.SVE_DB_ENCODED }} | base64 -d > secrets/database_url.env

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: aarch64-unknown-linux-musl
          args: "--release --locked"

      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          target: aarch64-unknown-linux-musl
          args: "--release --locked"

      - name: Package as archive
        run: |
          cd target/aarch64-unknown-linux-musl/release
          mv sve_backend bootstrap
          7z a lambda.zip bootstrap
          mv lambda.zip ../../../

      - name: Publish as lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: sve-backend
          zip_file: lambda.zip