name: Build and Deploy Release
on: [push]

env:
  SVE_CREDENTIALS_ENCODED: ${{ secrets.SVE_CREDENTIALS_ENCODED }} 
  SVE_EMAILS_ENCODED: ${{ secrets.SVE_EMAILS_ENCODED }} 
  IMAGE: sve_backend
  REGISTRY_HOSTNAME: eu.gcr.io/sve-backend

jobs:
  build-and-deploy-release:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - uses: 'google-github-actions/setup-gcloud@v0'

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      - run: mkdir -p secret
      - run: echo $SVE_CREDENTIALS_ENCODED | base64 -d > secret/credentials.json
      - run: echo $SVE_EMAILS_ENCODED | base64 -d > secret/email.json

      # Build the Docker image
      - name: Build
        run: |
          export TAG=work
          echo $TAG
          docker build -t "$REGISTRY_HOSTNAME"/"$IMAGE" \
            --build-arg SVE_CREDENTIALS_ENCODED="$SVE_CREDENTIALS_ENCODED" \
            --build-arg SVE_EMAILS_ENCODED="$SVE_EMAILS_ENCODED" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          export TAG=work
          echo $TAG
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG"
          docker tag "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG" "$REGISTRY_HOSTNAME"/"$IMAGE":latest
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE":latest
